- hosts: all
  become: yes
  tasks:
    - name: "Upload k8s-deploy"
      copy:
        src: "k8s-deploy"
        dest: "/root/"
    
    - name: "Aplicar configmap"
      shell: kubectl apply -f /root/k8s-deploy/7-mysql-configmap.yml

    - name: "Aplicar secret"
      shell: kubectl apply -f /root/k8s-deploy/7.1-mysql-secret.yml

    - name: "Aplicar mysql"
      shell: kubectl apply -f /root/k8s-deploy/7.2-mysql.yml

    - name: "Aplicar secret"
      shell: kubectl apply -f /root/k8s-deploy/7.3-deployment.yml

    - name: "Aplicar nodeport"
      shell: kubectl apply -f /root/k8s-deploy/7.4-nodeport-javadb.yml

    - shell: "kubectl get pods | grep mysql"
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "

# echo "create database SpringWebYoutubeTest;"| kubectl exec -it mysql-5fb6fb7fb4-9wdbn --tty -- mysql -uroot -ppassword_mysql 
# cat /root/k8s-deploy/1.2-dump-mysql.sql  | kubectl exec -it mysql-5fb6fb7fb4-9wdbn --tty -- mysql -uroot -ppassword_mysql SpringWebYoutubeTest

# # ansible-playbook -i hosts provisionar.yml -u ubuntu --private-key ~/Desktop/devops/treinamentoItau
